openapi: 3.1.0
info:
  title: Template Swagger API Documentation
  description: |-
    API documentation for the template projects, created by GDSC-DUT. This documentation offers detailed insights into the common API endpoints used across all templates.
  contact:
    email: contact@gdsc.dev
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: http://localhost:3000
paths:
  /profile/v1/me:
    get:
      tags:
        - profile
      summary: Get current user profile
      description: Retrieve detailed information about the currently authenticated user.
      operationId: getCurrentUserProfile
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Profile retrieved successfully
          content:
            application/json:
              schema:
                type: object
                required:
                  - status
                  - message
                  - data
                properties:
                  status:
                    type: string
                    example: "success"
                  message:
                    type: string
                    example: "Profile retrieved successfully"
                  data:
                    type: object
                    properties:
                      id: { type: string, format: uuid, example: "uuid-profile" }
                      full_name: { type: string, example: "Nguyen Van A" }
                      dob: { type: string, example: "1995-05-20" }
                      gender: { type: string, example: "Male" }
                      phone: { type: string, example: "0987654321" }
                      disability_status: { type: string, example: "Khiếm thị nhẹ" }
                      created_at: { type: string, example: "2023-10-01T08:00:00Z" }
                      devices:
                        type: array
                        items:
                          type: object
                          properties:
                            id: { type: string, example: "uuid-device-1" }
                            name: { type: string, example: "Máy đọc màn hình (Screen Reader)" }
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  status: { type: string, example: "error" }
                  message: { type: string, example: "Unauthenticated" }
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT